name: release-please (alpha from feature/*)

on:
  push:
    branches:
      - 'feature/*'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  alpha:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          target-branch: ${{ github.ref_name }}
          config-file: release-please-config.alpha.json
          manifest-file: .release-please-manifest.json
